apiVersion: v1
kind: Namespace
metadata:
  name: payg-production
  labels:
    environment: production
    app.kubernetes.io/part-of: payg-plus
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
