variable "aws_region"          { type = string; default = "ap-south-1" }
variable "environment"         { type = string; default = "dev" }
variable "vpc_cidr"            { type = string; default = "10.0.0.0/16" }
variable "az_count"            { type = number; default = 2 }
variable "kubernetes_version"  { type = string; default = "1.29" }
variable "node_instance_types" { type = list(string); default = ["t3.large"] }
variable "use_spot"            { type = bool; default = true }
variable "desired_nodes"       { type = number; default = 2 }
variable "min_nodes"           { type = number; default = 1 }
variable "max_nodes"           { type = number; default = 5 }
